#!/usr/bin/env bash
# Install and configure HAProxy as a load balancer

sudo apt-get -y update
sudo apt-get -y install haproxy
sudo chown $USER:USER /etc/haproxy/haproxy.cfg

sudo bash -c 'cat > /etc/haproxy/haproxy.cfg' <<EOL
frontend http
    bind *:80
    mode http
    default_backend web_servers

backend web_servers
    balance roundrobin
    server 660546-web-01 54.208.113.177
    server 660546-web-02 52.205.76.174
EOL

sudo service haproxy restart
