#!/usr/bin/env bash
# Install and configure HAProxy as a load balancer

sudo apt-get -y update
sudo apt-get install --no-install-recommends software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.4
sudo apt-get -y install haproxy=2.4.\*

sudo bash -c 'cat > /etc/haproxy/haproxy.cfg' <<EOL
frontend http
    bind *:80
    default_backend web_servers

backend web_servers
    balance roundrobin
    server 660546-web-01 54.208.113.177
    server 660546-web-02 52.205.76.174
EOL

sudo service haproxy restart
