#!/usr/bin/env bash
# Script to fix nginx unreachability by restoring the default server port
sudo cat /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx start
sudo service nginx restart
