#!/usr/bin/env bash
# Bash script to display output continuously and handles SIGTERM and SIGINT
# signlas, and finally clears up PID file created

echo $$ > /var/run/myscript.pid

cleanup(){
        rm -f /var/run/myscript.pid
        exit
}

trap 'echo "I hate the kill command"; cleanup' SIGTERM
trap 'echo "Y U no love me?!"' SIGINT
trap 'cleanup' SIGQUIT

while true; do
	echo "To infinity and beyond"
	sleep 2
done
