#!/usr/bin/env bash
# Bash script to display username, user id, and hoome diretory from /etc/passwd

while IFS=':' read -r username _ userid _ _ homedir _; do
	echo "$username:$userid:$homedir"
done < "/etc/passwd"
