#!/usr/bin/env bash
# Bash script to parse, group and sort Apache log file by IP and HTTP status 
# code

awk '{print $1, $9}' apache-access.log | sort | uniq -c | sort -rn |
	awk '{print $1, $2, $3}'
