#!/usr/bin/env bash
# Script to loop 10 times and display message based on condition.
counter=1
while [ $counter -le 20 ]; do
	if [ $counter = 4 ]; then
		echo "$counter"
		echo "bad luck from China"
	elif [ $counter = 9 ]; then
		echo "$counter"
		echo "bad luck from Japan"
	elif [ $counter = 17 ]; then
		echo "$counter"
		echo "bad luck from Italy"
	else
		echo "$counter"
	fi
	((counter++))
done
