#!/usr/bin/env bash
# Script to display the time for 12 hours 59 minutes

hours=0
while [ $hours -le 12 ]; do
	minutes=1
	echo "Hour: $hours"
	while [ $minutes -le 59 ]; do
		echo "$minutes"
		((minutes++))
	done
	((hours++))
done
