#!/usr/bin/env bash
# Bash script that edits /etc/hosts file
cp /etc/hosts ~/hosts.new
sed -i 's/127.0.0.1/127.0.0.2/g' /etc/hosts
printf "8.8.8.8	facebook.com" > /etc/hosts
cp -f ~/hosts.new /etc/hosts
