#!/usr/bin/env bash
# Script that displays all active IPv4 IPs on machine its executed
if command -v ip > /dev/null; then
	ifconfig | grep -oE 'inet ([0-9]{1,3}\.){3}[0-9]{1,3}' | awk '{print $2}'
fi
