#!/usr/bin/env bash
# Script to run Nginx as nginx, using 7 or less lines.
sudo sed -i 's/#user www-data/user nginx' /etc/nginx/nginx.conf
sudo sed -i 's/80/8080/g' /etc/nginx/sites-enabled/default
sudo chmod 644 /etc/nginx/nginx.conf
sudo -u nginx service nginx start
