#!/usr/bin/env bash
# Script to run Nginx as nginx
sudo sed -i 's/#user www-data/user nginx' /etc/nginx/nginx.conf
sudo sed -i 's/80/8080/g' /etc/nginx/sites-enabled/default
sudo chmod 644 /etc/nginx/nginx.conf
sudo chown nginx:nginx /etc/nginx/ -R
sudo -u nginx service nginx restart
